export const products = [
  {
    id: 1,
    title: "Camisa Hombre",
    stock: 5,
    price: 15000,
    description: "Camisa blanca entallada",
    Categoria: "Camisas de vestir",
    img: "https://res.cloudinary.com/dtpevosla/image/upload/v1680895473/Camisashombre_cfs85h.jpg",
  },
  {
    id: 2,
    title: "Remera Hombre",
    stock: 6,
    price: 9500,
    description: "Remera color negra ",
    Categoria: "Remeras informales",
    img: "https://res.cloudinary.com/dtpevosla/image/upload/v1680895847/CamisetaKK_f3e5u0.jpg",
  },
  {
    id: 3,
    title: "Remera Hombre",
    stock: 8,
    price: 12200,
    description: "Remera color negra y blanca ",
    Categoria: "Remeras informales",
    img: "https://res.cloudinary.com/dtpevosla/image/upload/v1680895984/Camiseta2_fae92r.png",
  },
  {
    id: 4,
    title: "Pantalon Mujer",
    stock: 4,
    price: 12200,
    description: "Pantalon negro  ",
    Categoria: "pantalones informales",
    img: "https://res.cloudinary.com/dtpevosla/image/upload/v1680896056/Pantalones1m-PhotoRoom.png-PhotoRoom_gbzz6r.png",
  },
];
